name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack -c Release --no-build -o out
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Namsku.BioRand.Messages
        path: out/**/*
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: |
          out/Namsku.BioRand.Messages.*.nupkg
